#!/bin/sh
cd "${0%/*}" || exit                                # Run from this directory
. ${WM_PROJECT_DIR:?}/bin/tools/RunFunctions        # Tutorial run functions
#------------------------------------------------------------------------------


restore0Dir

runApplication blockMesh

runApplication snappyHexMesh -overwrite

#runApplication freeSurPotV2 -withFunctionObjects 


runApplication decomposePar

runParallel PHIWaveCurSph2 -withFunctionObjects 

runApplication reconstructPar

runApplication postProcess -func writeCellCentres

##python3 zeta_plotter.py

#------------------------------------------------------------------------------
